version: '3.8'

services:
  postgres:
    image: postgres:latest
    container_name: dotnet-postgres
    environment:
      POSTGRES_USER: user
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: postgres
    ports:
      - "5433:5432"
    volumes:
      - ./doc/crebas.sql:/docker-entrypoint-initdb.d/crebas.sql
